#!/bin/sh

brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
if [[ $brightness == 0 ]]; then
		exit
fi

new_brightness=$((brightness-5000))
eval "sudo tee /sys/class/backlight/intel_backlight/brightness <<< $new_brightness"
