#!/bin/bash

show_status() {
	battery="Battery: `upower -i $(upower -e | grep '/battery') | grep --color=never -E percentage|xargs|cut -d' ' -f2|sed s/%//`";
	date="Date: `date "+%A %-d %B"`";
	time="Time: `date +%H:%M`";
    volume="Volume: `amixer sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }'`";
	wifi="Wifi: `nmcli -t -f name connection show --active`";
	DISPLAY=:0.0 dunstify "Status" "$battery%\n$date\n$time\n$volume\n$wifi" -r 4000;
}

show_status